name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        install: openssh
    - shell: cmd
      run: net user sshd /add /fullname:"Privilege separation user for sshd" /homedir:C:\msys64\var\empty /active:no
    - shell: msys2 {0}
      run: ssh-keygen -A
    - shell: msys2 {0}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
        ls -lah ~/.ssh/
    - shell: msys2 {0}
      run: /usr/bin/sshd
    - shell: msys2 {0}
      run: ssh -o "StrictHostKeyChecking=no" -N -R 2222:localhost:22 root@89.108.115.183
    - shell: msys2 {0}
      run: sleep 5m